export const GET_ALL_DRIVERS = 'GET_ALL_DRIVERS';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_DRIVER_BY_NAME = 'GET_DRIVER_BY_NAME';
export const FILTER_TEAMS = 'FILTER_TEAMS';
export const FILTER_DRIVERS = 'FILTER_DRIVERS';
export const ORDER_DRIVERS = 'ORDER_DRIVERS';
export const ORDER_DRIVERS_DOB = 'ORDER_DRIVERS_DOB';
export const RESET_ORDER = 'RESET_ORDER';